// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RankingDigi.Data;

#nullable disable

namespace RankingDigi.Migrations
{
    [DbContext(typeof(RankingContext))]
    [Migration("20260612015335_AddPlayerAvatar")]
    partial class AddPlayerAvatar
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RankingDigi.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PlayerId")
                        .HasColumnType("int");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("IX_AppUsers_Username");

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("RankingDigi.Models.Bracket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int>("Round")
                        .HasColumnType("int");

                    b.Property<int>("TournamentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TournamentId");

                    b.ToTable("Bracket");
                });

            modelBuilder.Entity("RankingDigi.Models.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Deck1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Deck2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Player1Id")
                        .HasColumnType("int");

                    b.Property<int>("Player2Id")
                        .HasColumnType("int");

                    b.Property<int>("WinnerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Date")
                        .HasDatabaseName("IX_Matches_Date");

                    b.HasIndex("Player1Id")
                        .HasDatabaseName("IX_Matches_Player1Id");

                    b.HasIndex("Player2Id")
                        .HasDatabaseName("IX_Matches_Player2Id");

                    b.HasIndex("WinnerId")
                        .HasDatabaseName("IX_Matches_WinnerId");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("RankingDigi.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Score")
                        .HasDatabaseName("IX_Players_Score");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("RankingDigi.Models.Tournament", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CurrentSwissRound")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Format")
                        .HasColumnType("int");

                    b.Property<string>("InviteCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("MaxPlayers")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("SwissRounds")
                        .HasColumnType("int");

                    b.Property<int>("TopCutSize")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InviteCode")
                        .IsUnique()
                        .HasDatabaseName("IX_Tournaments_InviteCode")
                        .HasFilter("[InviteCode] IS NOT NULL");

                    b.ToTable("Tournaments");
                });

            modelBuilder.Entity("RankingDigi.Models.TournamentMatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BracketId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsBye")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPlayed")
                        .HasColumnType("bit");

                    b.Property<int?>("LoserGoesToMatchId")
                        .HasColumnType("int");

                    b.Property<int>("MatchType")
                        .HasColumnType("int");

                    b.Property<int?>("NextMatchId")
                        .HasColumnType("int");

                    b.Property<int?>("NextMatchPosition")
                        .HasColumnType("int");

                    b.Property<int?>("Player1Id")
                        .HasColumnType("int");

                    b.Property<int?>("Player2Id")
                        .HasColumnType("int");

                    b.Property<int>("Round")
                        .HasColumnType("int");

                    b.Property<int>("TournamentId")
                        .HasColumnType("int");

                    b.Property<int?>("WinnerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BracketId");

                    b.HasIndex("LoserGoesToMatchId");

                    b.HasIndex("NextMatchId");

                    b.ToTable("TournamentMatches");
                });

            modelBuilder.Entity("RankingDigi.Models.TournamentPlayer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Deck")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GuestName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("SwissDraws")
                        .HasColumnType("int");

                    b.Property<int>("SwissLosses")
                        .HasColumnType("int");

                    b.Property<int>("SwissPoints")
                        .HasColumnType("int");

                    b.Property<int>("SwissWins")
                        .HasColumnType("int");

                    b.Property<int>("TournamentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("TournamentId");

                    b.ToTable("TournamentPlayers");
                });

            modelBuilder.Entity("RankingDigi.Models.AppUser", b =>
                {
                    b.HasOne("RankingDigi.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Player");
                });

            modelBuilder.Entity("RankingDigi.Models.Bracket", b =>
                {
                    b.HasOne("RankingDigi.Models.Tournament", "Tournament")
                        .WithMany("Brackets")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("RankingDigi.Models.TournamentMatch", b =>
                {
                    b.HasOne("RankingDigi.Models.Bracket", null)
                        .WithMany("Matches")
                        .HasForeignKey("BracketId");

                    b.HasOne("RankingDigi.Models.Tournament", "LoserGoesToMatch")
                        .WithMany()
                        .HasForeignKey("LoserGoesToMatchId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("RankingDigi.Models.TournamentMatch", "NextMatch")
                        .WithMany()
                        .HasForeignKey("NextMatchId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("LoserGoesToMatch");

                    b.Navigation("NextMatch");
                });

            modelBuilder.Entity("RankingDigi.Models.TournamentPlayer", b =>
                {
                    b.HasOne("RankingDigi.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("RankingDigi.Models.Tournament", "Tournament")
                        .WithMany("TournamentPlayers")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("RankingDigi.Models.Bracket", b =>
                {
                    b.Navigation("Matches");
                });

            modelBuilder.Entity("RankingDigi.Models.Tournament", b =>
                {
                    b.Navigation("Brackets");

                    b.Navigation("TournamentPlayers");
                });
#pragma warning restore 612, 618
        }
    }
}
